# renderdoctools/core.py
"""RenderDoc script execution engine.

Locates the bundled RenderDoc, generates temp analysis scripts,
executes them via qrenderdoc --python, and parses JSON output.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

# Workspace root: parent of the renderdoctools/ package
WORKSPACE_ROOT = Path(__file__).resolve().parent.parent

# Directory containing template scripts
SCRIPTS_DIR = Path(__file__).resolve().parent / "scripts"


def find_renderdoc() -> Path:
    """Locate bundled qrenderdoc.exe. Raises FileNotFoundError if missing."""
    # Search for RenderDoc in tools/ — supports both "renderdoc" and versioned names
    tools_dir = WORKSPACE_ROOT / "tools"
    for name in ["renderdoc", "RenderDoc_DX9", "RenderDoc_1.43_64"]:
        qrd = tools_dir / name / "qrenderdoc.exe"
        if qrd.is_file():
            return qrd
    # Also try any RenderDoc_* directory
    if tools_dir.is_dir():
        for d in sorted(tools_dir.iterdir(), reverse=True):
            if d.name.lower().startswith("renderdoc") and d.is_dir():
                qrd = d / "qrenderdoc.exe"
                if qrd.is_file():
                    return qrd
    raise FileNotFoundError(
        "RenderDoc not found in %s\n"
        "Run 'python verify_install.py' to auto-install, or download from "
        "https://github.com/Kim2091/renderdoc/releases and extract to tools/" % tools_dir
    )


def run_script(
    script_name: str,
    capture_path: str,
    config: dict | None = None,
    timeout: int = 120,
) -> dict:
    """Execute a RenderDoc analysis script and return parsed JSON output."""
    qrd = find_renderdoc()
    config = config or {}

    local_tmp = WORKSPACE_ROOT / "tmp"
    local_tmp.mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="rdtools_", dir=str(local_tmp)) as tmpdir:
        tmpdir = Path(tmpdir)
        output_path = tmpdir / "output.json"
        config_path = tmpdir / "config.json"
        script_path = tmpdir / "script.py"

        full_config = {
            "capture": str(Path(capture_path).resolve()),
            "output": str(output_path),
            **config,
        }
        config_path.write_text(json.dumps(full_config))

        template_path = SCRIPTS_DIR / (script_name + ".py")
        if not template_path.is_file():
            raise FileNotFoundError("Script template not found: %s" % template_path)

        base_header = (SCRIPTS_DIR / "_base_header.py").read_text()
        template_body = template_path.read_text()

        # Indent template body for try/except wrapper
        indented_body = "\n".join(
            ("    " + line if line.strip() else line)
            for line in template_body.splitlines()
        )

        full_script = (
            "# Generated by renderdoctools -- do not edit\n"
            "_CONFIG_PATH = %r\n\n" % str(config_path.as_posix())
            + base_header
            + "\ntry:\n"
            + indented_body
            + "\nexcept Exception as _e:\n"
            + "    _shutdown()\n"
            + "    _write_error('Script error: ' + str(_e))\n"
            + "\nimport os; os._exit(0)\n"
        )
        script_path.write_text(full_script)

        result = subprocess.run(
            [str(qrd), "--python", str(script_path)],
            capture_output=True,
            text=True,
            timeout=timeout,
        )

        if not output_path.is_file():
            err = result.stderr.strip() if result.stderr else "No output produced"
            raise RuntimeError(
                "Script '%s' failed (exit %d): %s"
                % (script_name, result.returncode, err)
            )

        return json.loads(output_path.read_text())


def format_table(rows: list[dict], columns: list[str]) -> str:
    """Format a list of dicts as an aligned text table."""
    if not rows:
        return "(no results)"

    widths = {c: len(c) for c in columns}
    for row in rows:
        for c in columns:
            val = str(row.get(c, ""))
            widths[c] = max(widths[c], len(val))

    header = "  ".join(c.ljust(widths[c]) for c in columns)
    sep = "  ".join("-" * widths[c] for c in columns)
    lines = [header, sep]

    for row in rows:
        line = "  ".join(str(row.get(c, "")).ljust(widths[c]) for c in columns)
        lines.append(line)

    return "\n".join(lines)
